def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--mode', type=str, default='train', help='train or infer')
    parser.add_argument('--batch_size', type=int, default=32, help='batch size')
    parser.add_argument('--epochs', type=int, default=100, help='number of epochs')
    parser.add_argument('--lr', type=float, default=0.001, help='learning rate')
    parser.add_argument('--weight_decay', type=float, default=0.0001, help='weight decay')
    parser.add_argument('--device', type=str, default='cuda:0', help='device')
    parser.add_argument('--save_dir', type=str, default='checkpoints', help='save directory')
    parser.add_argument('--load_dir', type=str, default='checkpoints', help='load directory')
    parser.add_argument('--save_name', type=str, default='model', help='save name')
    parser.add_argument('--load_name', type=str, default='model', help='load name')
    parser.add_argument('--save_interval', type=int, default=10, help='save interval')
    parser.add_argument('--log_interval', type=int, default=10, help='log interval')
    parser.add_argument('--seed', type=int, default=42, help='random seed')
    parser.add_argument('--num_workers', type=int, default=4, help='number of workers')
    parser.add_argument('--pin_memory', type=bool, default=True, help='pin memory')
    parser.add_argument('--shuffle', type=bool, default=True, help='shuffle')
    parser.add_argument('--drop_last', type=bool, default=True, help='drop last')
    parser.add_argument('--num_attention_heads', type=int, default=8, help='number of attention heads')
    parser.add_argument('--attention_probs_dropout_prob', type=float, default=0.1, help='attention probs dropout prob')
    parser.add_argument('--hidden_dropout_prob', type=float, default=0.1, help='hidden dropout prob')
    parser.add_argument('--max_length', type=int, default=50, help='max length')
    parser.add_argument('--input_dim_drug', type=int, default=2586, help='input dim drug')
    parser.add_argument('--output_dim', type=int, default=2560, help='output dim')
    parser.add_argument('--cellencoder', type=str, default='cellTrans', help='cell encoder type')
    parser.add_argument('--celldataset', type=int, default=0, help='cell dataset type')
    parser.add_argument('--omic', type=str, default='exp,mut,cn', help='omic type')
    args = parser.parse_args()
    return args 
